name: Notify Slack on Branch Merge

on:
  pull_request:
    types:
      - closed  # triggers when PR is closed (merged or not)

jobs:
  notify-on-merge:
    if: github.event.pull_request.merged == true  # run only if PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification for Merge
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":twisted_rightwards_arrows: *Branch Merge Alert*\n*Merged by:* ${{ github.actor }}\n*From:* `${{ github.event.pull_request.head.ref }}`\n*To:* `${{ github.event.pull_request.base.ref }}`\n*Title:* _${{ github.event.pull_request.title }}_\n*PR Link:* <${{ github.event.pull_request.html_url }}|View Pull Request>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
